<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="doss.css" type="text/css">
<title>Struts2CmisExplorer</title>
</head>

<table width="950" align="center" border="0" cellpadding="0" cellspacing="0" height="52">
  <tbody>
  	<tr>
		<td valign="middle" width="680" height="50">
			<a href="http://aegif.jp/"><img src="./images/aegif.gif" border="0" height="50"></a>
		</td>
		<td colspan="2" valign="top" height="50">
			<div class="style4" align="right">
	        <div align="right"><br>
	        	<span class="style15">  | 
	        		<a href="http://aegif.jp/" target="_blank">aegif</a> | 
	        		<a href="http://aegif.typepad.jp/">blog aegif</a> | 
	        		<a href="http://www.alfresco.com/" target="_blank">Alfresco</a> | 
	        		<a href="http://aegif.jp/inquiry.html" target="_blank">CONTACT</a> |
	        		<br/>
	            	<br/>
					aegif explores ground in frontier             
				</span>
			</div>
	    	</div>
		</td>
	</tr>
	<tr>
		<td height="2"></td>
		<td width="190"></td>
		<td width="80"></td>
	</tr>
  </tbody>
</table>
